### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by McGiverGim** [stpettersens/gulp-debian#11]
Hi @stpettersens ! Are you going to release a new version soon with the latest changes? I want to use it here https://github.com/betaflight/betaflight-configurator/pull/833 but I need the latest changes.

Thanks!

**Comment by stpettersens** [comment]
Hi Miguel. I will release tonight after work. Sorry for the delay. Should
be around 1900 GMT.

**Comment by McGiverGim** [comment]
Thanks!

**Comment by stpettersens** [comment]
Just refreshing the dependencies. I'll let you know when I publish.

**Comment by stpettersens** [comment]
@McGiverGim : [gulp-debian@0.1.6](https://libraries.io/npm/gulp-debian/0.1.6) now published. Does not appear on link yet, but `npm-search` should yield it.

Thank you again for your contributions.

**Comment by McGiverGim** [comment]
Tested and works great!! Thanks for your work :)

I close the issue...
