### ISSUE TITLE
postinst script support

### ISSUE THREAD

**Issue by OlafRadicke** [stpettersens/gulp-debian#4]
Hi!

Same question like the changelog request:
Do you have a idea for a implementation of a postinst script support?
Do you prefer a embedded solution in the Gulpfile.js or more as an external file?

**Comment by stpettersens** [comment]
I do like this idea! I would implement similarly to CHANGELOG support. 
Please see [issue #3](https://github.com/stpettersens/gulp-debian/issues/3).

**Comment by OlafRadicke** [comment]
Okay, here my format suggestion for the embedded way:
```
gulp.task('dist_deb', function () {
    return gulp.src(['./bin/hello-world'])
        .pipe(deb({
            package: 'hello-world',
            version: '3.1.7',
            section: 'base',
            priority: 'optional',
            architecture: 'all',
            maintainer: 'Olaf Radicke <o.radicke@meteocontrol.de>',
            description: 'Only a example',
            preinst: [ "addgroup foo-prog"],
            postinst: [ "systemctl daemon-reload", "systemctel enable foo-prog"]
            _target: '/usr/bin/',
            _out: 'dist'
        }))
});
```

**Comment by stpettersens** [comment]
Looks excellent. Nice work!

**Comment by stpettersens** [comment]
This is now (at least initially) implemented for preinst and postinst under version 0.1.4.

**Comment by OlafRadicke** [comment]
Thank you very much!

**Comment by stpettersens** [comment]
You're welcome. Happy New Year!
